### PR TITLE
Fix astro package entrypoint types

### PR DESCRIPTION
**Pull request by MoustaphaDev**
### 📓 What's in there?

Fixes https://github.com/vercel/speed-insights/issues/54. The `types` field of the `astro` export didn't point to any existing file, so it couldn't be resolved.
I'm not sure why the fix in https://github.com/vercel/speed-insights/pull/41 supposedly worked for some people, but this should hopefully fix it for everyone.

### 🧪 How to test?

```sh
# build the package
pnpm -F @vercel/speed-insights build

# cd into the astro example app
cd apps/astro

# install typescript and @astrojs/check
pnpm i -D typescript @astrojs/check

# run `astro check` 
pnpm astro check
```

This should work now, but before it caused an error
<details>
<summary><b>Before</b></summary>

```sh
> astro "check"

22:55:55 Types generated 473ms
22:55:55 [check] Getting diagnostics for Astro files in /home/coding/speed-insights/apps/astro...
src/components/BaseHead.astro:5:27 - error ts(2307): Cannot find module '@vercel/speed-insights/astro' or its corresponding type declarations.

5 import SpeedInsights from '@vercel/speed-insights/astro';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/components/BaseHead.astro:49:12 - warning ts(6133): 'speedInsightsBeforeSend' is declared but its value is never read.

49   function speedInsightsBeforeSend(data){
              ~~~~~~~~~~~~~~~~~~~~~~~

Result (14 files): 
- 1 error
- 0 warnings
- 1 hint
```
</details>

<details>
<summary><b>After</b></summary>

```sh
> astro "check"

22:58:46 Types generated 425ms
22:58:46 [check] Getting diagnostics for Astro files in /home/coding/speed-insights/apps/astro...
src/components/BaseHead.astro:49:12 - warning ts(6133): 'speedInsightsBeforeSend' is declared but its value is never read.

49   function speedInsightsBeforeSend(data){
              ~~~~~~~~~~~~~~~~~~~~~~~

Result (14 files): 
- 0 errors
- 0 warnings
- 1 hint
```
</details>

The type error was also surfaced in the IDE, but it's resolved fine now
<details>
<summary><b>Before</b></summary>

Screenshot from 2024-02-12 23-54-35

</details>

<details>
<summary><b>After</b></summary>

Screenshot from 2024-02-13 01-27-43-edit

</details>

### CODE REVIEW

**Comment by MoustaphaDev** [comment]
Would love if you can have a look at this @tobiaslins!

**Comment by rochajulian** [comment]
> Would love if you can have a look at this @tobiaslins (or any other maintainer)!

Second this

**Review by feugy — APPROVED** [review]
Thanks for you contribution! 
Let's try it in the wild.

**Review by feugy — APPROVED** [review]

**Comment by feugy** [comment]
@MoustaphaDev , @rochajulian, I've released 1.0.10. 
Please try it out and let us know.

**Comment by MoustaphaDev** [comment]
I'm so confused as well, now I can't even reproduce this error anymore with 1.0.9.
The Astro language server and typescript plugin were updated yesterday, so I suspect that might have helped solve the problem.
1.0.10 is working as well. I guess reverting when we find any bug, as you said, would be best 🤷‍♂️

**Pull request merged**
